services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # External services port range
    environment:
      - SERVICES=s3,dynamodb,cloudwatch,sqs
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PERSISTENCE=1
    volumes:
      - "./init-aws.sh:/etc/localstack/init/ready.d/01-init-aws.sh"
      - "localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/health?reload"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  localstack_data:
    driver: local