spring:
  application:
    name: ddd-synchronizer

sqs:
  region: ${AWS_REGION:us-east-1}
  endpoint: ${SQS_ENDPOINT:}
  queue-url: ${SQS_QUEUE_URL:}
  max-number-of-messages: 10
  wait-time-seconds: 20

logging:
  level:
    root: INFO
    com.github.sanmoo.ddd.synchronizer: DEBUG
